### ISSUE TITLE
Boote deserten, treiben ab?

### ISSUE THREAD

**Issue by christian2526** [christian2526/Domination-3-Lingor#20]
Boote deserten, treiben ab? Dadurch Ticket loss.

**Comment by phumberdroz** [comment]
Vielleicht doch wieder direkt an das dock stellen ?

**Comment by Desty84** [comment]
enableSimulation false bis jmd einsteigt?
Würde zwar komisch aussehen, aber sollte das abtreiben verhindern...

**Comment by christian2526** [comment]
Fixed, der Despawn Prevention Marker hat gar nicht funktioniert, der ist jetzt Hardcoded
