### ISSUE TITLE
SM: 1 etc...  Kill the Officer

### ISSUE THREAD

**Issue by phumberdroz** [christian2526/Domination-3-Lingor#38]
Wenn man ihn tötet failed die Side.

**Comment by phumberdroz** [comment]
könnte an mir gelegen haben. Hatte setcapetive an und das andere mal wurden sie von KI getötet.

**Comment by phumberdroz** [comment]
12 ebenso buggy

**Comment by christian2526** [comment]
ace macht killed eh kaputt, dadurch funzt es nicht. Workaround if (true) then. Auf später verschoben
